config/routes.rb
Rails.application.routes.draw do
root to: 'recipes#index'

 get '/signup' => 'users#new'
 post '/users' => 'users#create'

 get '/signin' => 'sessions#new'
 post '/signin' => 'sessions#create'
 get '/signout' => 'sessions#destroy'

 resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize 
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page. If you want to see these recipes, please sign up!"
      redirect_to '/signup'
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authorize, only: [:new]

  def index
    @recipes = RecipeService.get_meal()
  end

  def new
    @recipes = RecipeService.get_meal()
    render :new
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password] )
    if @user
      flash[:notice] = "You've signed in"
      session[:user_id] = @user.id
      redirect_to "/recipes/new"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up"
      session[:user_id] = @user.id 
      redirect_to "/recipes/new"
    else
      flash[:alert] = "There was a problem signing up"
      redirect_to '/signup'
    end
  end

    private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class ="container">
      <div class = "box">
        <% if current_user %>
          <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
        <% else %>
          <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
        <% end %>

        <%= flash[:alert] %>
        <%= flash[:notice] %>
        
        <%= yield %>
        </div>
    </div>
    <footer> Jozy, Tyler, and Zinfira (c) 2020 </footer>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Rando Recipes</h1>
<% @recipes["meals"].each do |meal| %>
  <h2>Name: <%=meal["strMeal"]%></h2>
  <h2>video instruction: <h4><a href="<%=meal["strYoutube"]%>">Link to Youtube</a></h4>
  <br>
  <p>If you want to see more recipes in depth, click here! <%= link_to "Recipes", new_recipe_path %></p>
<% end %>

app/views/recipes/new.html.erb
<h1>Rando Recipes</h1>

<% @recipes["meals"].each do |meal|%>
<ul>

<h2>Name: <%=meal["strMeal"]%></h2>
<br>
<h3> Instructions:</h3> <p><%=meal["strInstructions"]%></p>
<br>
<h4>Ingredients: </h4>
<p><%=meal["strIngredient1"]%></p>
<p><%=meal["strIngredient2"]%></p>
<p><%=meal["strIngredient3"]%></p>
<p><%=meal["strIngredient4"]%></p>
<p><%=meal["strIngredient5"]%> </p>
<p><%=meal["strIngredient6"]%></p>
<br>
<h4><a href="<%=meal["strYoutube"]%>">Link to Youtube</a></h4>
 <h4><%= link_to "Return to Home", recipes_path %></h4>
</ul>
 <% end %>

app/views/users/new.html.erb
<h1> Sign up </h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>